repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest tests
        pass_filenames: false
        always_run: true
      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pytest --cov --cov-fail-under=70
        types: [python]
        pass_filenames: false