apiVersion: v1
kind: Pod
metadata:
  name: flask-server-pod
  labels:
    environment: test
    app: my_flask
spec:
  containers:
    - name: my-flask
      image: ghcr.io/ulfx/devops21_cicd_final/my_flask:latest
  imagePullSecrets:
    - name: regcred