name: Docker Image CI

on:
  push:
    branches: [ "feature-*" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
    run: |
          docker build . --tag ghcr.io/Rockyraccoon/devops21_cicd_final/my_flask:${{ github.head_ref }}${{ github.sha }}
          docker run ghcr.io/Rockyraccoon/my_flask:${{ github.head_ref }}${{ github.sha }}
          docker push ghcr.io/Rockyraccoon/my_flask:${{ github.head_ref }}${{ github.sha }}



