name: Docker Image CI Main

on:
  workflow_run:
    workflows: [Python application] 
    types: [completed]
    branches: [main]

jobs:   
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/ulfx/devops21_cicd_final/my_flask:latest
 



