name: Docker Image CI

on:
  push:
    branches: [ "feature-*" ]
jobs:    
  docker:
    if: ${{ github.ref == 'refs/heads/main' }
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to $GITHUB_REF"      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/ulfx/devops21_cicd_final/my_flask:${{GITHUB_REF}}${{github.sha}}
 



